---
name: Actions CI
on:
  pull_request: {}
  push:
    branches:
      - main
      - development
    tags:
      - 'v*.*.*'

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.9
        task:
          - name: Ottr API Unit Test
            command: |
              tox -e coverage-api
          - name: Merge Coverage
            command: |
              coveralls-lcov -v -n .coverage.api > coverage.json
    name: "Python ${{ matrix.python }}/${{ matrix.task.name }}"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.command }}